apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-toolkit
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/bluecloudy/devspace-vcluster-argocd-demo
    targetRevision: HEAD
    kustomize:
      images:
      - blcloudy/devops-toolkit:latest
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
